---
title: ضوء اليراعة
hero_image: images/banner.png
description:
  - Use a Raspberry Pi Pico to make an LED firefly that flashes in a particular
  - pattern, just like fireflies in nature
version: 4
listed: true
copyedit: true
last_tested: "2021-03-26"
steps:
  - 
    title: سوف تصنع
  - 
    title: إعداد ال Raspberry Pi Pico الخاص بك
  - 
    title: إشعال LED ال Raspberry Pi Pico
    completion:
      - engaged
  - 
    title: أشعل اليراعة الخاص بك
  - 
    title: اجعل اليراعة تومض
  - 
    title: إضافة مفتاحًا كهربائياً
    completion:
      - internal
  - 
    title: اختبار سريع
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: قم بترقية او تطوير مشروعك
  - 
    title: ما التالي؟
